### ISSUE TITLE
Bug: CI Compilation is failing for ESP8266 boards

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/ArduinoIoTCloud#216]
I believe this is due to some background change within the `compile-examples` action or within the tooling used for compilation which results in **a ESP8266 core != 2.5.0 being used for CI build**. (Also see https://github.com/arduino-libraries/ArduinoMqttClient/pull/33).

@per1234 Can you please fix this?

**Comment by per1234** [comment]
Should be fixed by https://github.com/arduino/arduino-cli/pull/1140

The fix will only become available to the CI system when the next release of Arduino CLI (presumably 0.15.0) comes out. at that time, the workaround for this issue (https://github.com/arduino-libraries/ArduinoIoTCloud/pull/222) should be reverted.
