### ISSUE TITLE
BearSSLClient::write fails to send data buffer > 512 bytes

### ISSUE THREAD

**Issue by pennam** [arduino-libraries/ArduinoIoTCloud#300]
Opened to track this issue https://github.com/arduino-libraries/ArduinoBearSSL/issues/60 and related PR https://github.com/arduino-libraries/ArduinoBearSSL/pull/61

**Comment by Jeroen88** [comment]
The problem is [here](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/112ec82160e15e2a8f5e3945c93d2aa8516e3efa/src/tls/BearSSLClient.cpp#L92): 
- If more than 512 bytes are written, then result == 512. In the next 'while' round, size is still it's original value, which is incorrect. This is working:

```
size_t BearSSLClient::write(const uint8_t *buf, size_t size)
{
  size_t written = 0;
  size_t toWrite = size;

  while (written < toWrite) {
    int result = br_sslio_write(&_ioc, buf, size);

    if (result < 0) {
      break;
    }

    buf += result;
    written += result;
    size -= result;
  }

  if (written == toWrite && br_sslio_flush(&_ioc) < 0) {
    return 0;
  }

  return written;
}

```
