### ISSUE TITLE
When registering the first Lora device allow to reuse an existing TTN account

### ISSUE THREAD

**Issue by Bodobolero** [arduino-libraries/ArduinoIoTCloud#320]
The TTN network is much older and much more used than the Arduino IoT cloud.
Thus it is very likely that a new user of the Arduino IoT cloud already has a TTN account when registering the first Lora device.
However there is no option in the Arduino IoT cloud to associate an existing TTN account. There is always a new one created specifically for the Arduino IoT cloud.
I think this is a suboptimal design and an option should be added to associate an existing TTN account.

**Comment by per1234** [comment]
Hi @Bodobolero. Thanks for taking the time to submit this valued suggestion for [the Arduino IoT Cloud](https://docs.arduino.cc/cloud/iot-cloud).

I'm closing this issue because the correct place to report issues or make feature requests specific to the Arduino IoT Cloud is in its dedicated category on the Arduino forum:
https://forum.arduino.cc/c/software/iot-cloud/152

This is the correct place to report issues specific to the code base or documentation of the ArduinoIoTCloud library hosted in this repository.

If you haven't done so already, please make a report there. Thanks!

**Comment by Bodobolero** [comment]
@per1234 yes I doubted this is the right place because it is the library source code.
However I was directed to this repository by the support forum you referred to above when I asked above for a place to publicly track the issue.

I suggest that you internally discuss how to make the process of feedback to your closed source code (server side of AIoT cloud) more open and transparent. Arduino is all about openness and open source and it would be good to have at least the issue tracking and feature requests in a public, open github repo.
